### ISSUE TITLE
Please add support for Options just like in the .Net socket - e.g. add custom TImeOut/SubProtocol

### ISSUE THREAD

**Issue by studentutu** [psygames/UnityWebSocket#20]
Please add support for Options just like in the .Net socket - e.g. add custom TImeOut/SubProtocol.

Just make another class inside Core folder - UniformSocketOptions.cs, let it be a simple class and copy paste fields from the .Net Socket Options.

Also don't forget to add SetOptions(UniformSocketOptions) under the IWebSocket interface

**Comment by psygames** [comment]
@studentutu  Thanks for your suggestion, I will think about it.

**Comment by psygames** [comment]
Subprotocol supported at version 2.6.5 .
