### ISSUE TITLE
发包线程Task.Delay(1),导致手机CPU占用过高，发热严重

### ISSUE THREAD

**Issue by coidx** [psygames/UnityWebSocket#24]
https://github.com/psygames/UnityWebSocket/blob/89aedd6c3b2c6cde99a7ef0e30801393498a8357/Assets/UnityWebSocket/Scripts/Runtime/Implementation/NoWebGL/Default/WebSocket.cs#L188

**Comment by coidx** [comment]
测试机：iPhone6，iPhone7

**Comment by Bian-Sh** [comment]
建议你使用 UniTask ，Task 目前在 Webgl 上应该是不起作用的。
你可以测试下 Task.Delay（1） 究竟有没有真正的帮你延迟

**Comment by coidx** [comment]
> 建议你使用 UniTask ，Task 目前在 Webgl 上应该是不起作用的。 你可以测试下 Task.Delay（1） 究竟有没有真正的帮你延迟

首先我是原生端测试的，延迟是有的，但是Task.Delay(1)太短频繁的执行导致cpu占用率会增加很多。目前我们这边解决方式通触发的方式，修改后cpu明显的降低且发热也低了
