### ISSUE TITLE
The received content seems incorrect, which is concatenated with previous received content.

### ISSUE THREAD

**Issue by zhengyi73** [psygames/UnityWebSocket#25]
![image](https://user-images.githubusercontent.com/8935873/156277448-66b9d885-623d-4489-90c4-f98870eead20.png)
Compiled to Mac and In Unity editor have this problem, but WebGL is fine.

**Comment by sps100** [comment]
2.6.0遇到了相同的问题，onmessage里面会有之前收到的数据，换成2.5.0没问题

**Comment by psygames** [comment]
Sorry all, it's a low-level mistake, fix in v2.6.1 please update now.
