### ISSUE TITLE
Can't connect to wss again!

### ISSUE THREAD

**Issue by mrss2707** [psygames/UnityWebSocket#26]
I'm using version 2.6.4 connect to my wss server it's said "Unable to connect to the remote server" and then when I switch my server to ws it work normally.

**Comment by Woody4618** [comment]
I am having the same problem

**Comment by psygames** [comment]
@mrss2707 @Woody4618 You must use an authenticated certificate to your wss server.

**Comment by psygames** [comment]
使用 wss 方式连接，需要以下几个东西：
1. 一个可访问的远程主机。
2. 一个域名绑定到这个远程主机。
3. 一个正式的 SSL 证书（认证过的），绑定到这个域名。
在这个远程主机上启动 websocket server，并正确配置这个 SSL 证书，这样基本就能解决 wss 无法连接的问题了。
