### ISSUE TITLE
请问，可以支持 git 导入么？

### ISSUE THREAD

**Issue by cupen** [psygames/UnityWebSocket#28]
导入会方便一些，免于文件传来传去麻烦。
https://docs.unity3d.com/Manual/upm-ui-giturl.html
https://docs.unity3d.com/Manual/upm-git.html#syntax

**Comment by psygames** [comment]
可以的，之前支持过一段时间，感觉用的人不多，我就关闭了。

**Comment by psygames** [comment]
已经支持 git 导入了，参考： [安装方法](https://github.com/psygames/UnityWebSocket?tab=readme-ov-file#%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95)

**Comment by cupen** [comment]
@psygames 棒!
