### ISSUE TITLE
环境不支持Blob会报错，需要判断Blob是否是undefined

### ISSUE THREAD

**Issue by colden-rabbit** [psygames/UnityWebSocket#29]
![image](https://github.com/psygames/UnityWebSocket/assets/34415306/6f8b2e10-9836-44b0-86e7-3f1137b96e71)
要先判断Blob是否undefined，否则会报错，然后接收字符串就走不到下面的判断分支

**Comment by psygames** [comment]
Fixed at [v2.8.0](https://github.com/psygames/UnityWebSocket/releases/tag/v2.8.0)
