### ISSUE TITLE
消息可能无法正常发送的Bug

### ISSUE THREAD

**Issue by huangkumao** [psygames/UnityWebSocket#30]
![image](https://github.com/psygames/UnityWebSocket/assets/10599192/edb6db26-7bdd-4878-a06b-07049b06a956)

在SendBufferAsync的163行sendQueue.Enqueue(buffer); 把消息压进队列的时候 下面的SendTask()线程可能已经退出了 导致消息需要到下次发送其他消息的时候 才会一起发送

**Comment by psygames** [comment]
确实有这个问题，我研究一下

**Comment by psygames** [comment]
Fixed at [v2.8.0](https://github.com/psygames/UnityWebSocket/releases/tag/v2.8.0)
