### ISSUE TITLE
100% CPU Utilization 

### ISSUE THREAD

**Issue by nukadelic** [psygames/UnityWebSocket#34]
Getting 100% GPU Utilization when hitting play inside the unity editor with your demo script ( UnityWebSocketDemo.cs )
![image](https://github.com/user-attachments/assets/be92e389-0e9c-47f2-b926-a5dfa903d497)

**Comment by psygames** [comment]
请先使用 v2.7.0 版本

**Comment by psygames** [comment]
Fixed in [v2.8.1](https://github.com/psygames/UnityWebSocket/releases), please reinstall the new version.
