### ISSUE TITLE
2.8.2 版本在团结引擎上（1.2）以 upm 方式使用，微信小游戏运行时报错。

### ISSUE THREAD

**Issue by GarfieldJiang** [psygames/UnityWebSocket#37]
plugin.js:93 missing function: WebSocketSetOnOpen(env: macOS,mg,1.06.2407110; lib: 3.5.1)

**Comment by shuimoyer** [comment]
plugin.js:93 missing function: WebSocketSetOnOpen(env: Windows,mg,1.06.2407120; lib: 3.5.1)

**Comment by shuimoyer** [comment]
@GarfieldJiang  看看.jslib的导出设置， minigame平台是否勾选

**Comment by GarfieldJiang** [comment]
> @GarfieldJiang 看看.jslib的导出设置， minigame平台是否勾选

是的，需要在 UPM 版本里也加上这个。似乎不会影响 Unity 的使用。

**Comment by psygames** [comment]
Fixed in [v2.8.3](https://github.com/psygames/UnityWebSocket/releases)
