### ISSUE TITLE
在WebGL下，如果服务端先发送一条消息过来后再断开连接，会漏掉消息。

### ISSUE THREAD

**Issue by xianwx** [psygames/UnityWebSocket#40]
比如服务端在处理异常情况时，先发一条带Error信息的消息过来，然后发完那条消息后，关闭连接。在Editor下，没啥问题，先处理了那条Error消息，再处理关闭连接。但是在WebGL上，那条Error消息就直接没收到了，必须加点间隔发消息才可以。

**Comment by psygames** [comment]
麻烦问下，Error消息指的是什么？是onError 回调吗？服务器主动触发 onError 吗？可以在QQ群里详细交流一下、

**Comment by psygames** [comment]
有没有可能是服务器那边处理逻辑的问题，SendMessage 还没发送成功，然后就关闭了链接？

**Comment by xianwx** [comment]
你好，我加QQ群详细交流下吧。
