### ISSUE TITLE
未关闭 WebSocket 的条件下调用 `Application.Quit()` 会导致 Unity 应用程序未响应

### ISSUE THREAD

**Issue by AkagawaTsurunaki** [psygames/UnityWebSocket#41]
**复现步骤：**
假设已将 Unity 打包至 Windows 平台：
1. 以 Unity 为 WebSocket 客户端的方式连接到一个 WebSocket 服务器，连接成功。
2. 利用按钮触发事件，调用 `Application.Quit()`。
3. Unity 应用程序进入了未响应的状态。

**其他信息：**
Unity: 2021.3.44f1c1
Target platform: Windows 11
UnityWebSocket: 2.8.5

**暂时的解决方案？**
在调用 `Application.Quit()` 前使用 `CloseAsync()` 关闭 WebSocket 连接。

**Comment by psygames** [comment]
Fix on[ v2.8.6](https://github.com/psygames/UnityWebSocket/releases/tag/v2.8.6)
